services:
  redis:
    image: redis:7-alpine
    container_name: beyefendisinemaci-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    image: ${APP_IMAGE}
    container_name: beyefendisinemaci-app
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      TMDB_API_KEY: ${TMDB_API_KEY}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      CLOUDFRONT_URL: ${CLOUDFRONT_URL}
    depends_on:
      - redis

volumes:
  redis-data:
